title: JINJIA LIU
#logo: /assets/IMG_9093.jpeg
description: Aspiring cybersecurity professional with hands-on experience in network security, vulnerability assessments, and incident response, eager to apply knowledge of industry tools and best practices in an entry-level cybersecurity role.
#show_downloads: true
theme: jekyll-theme-minimal
